// <auto-generated />
using System;
using ElectionProject;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace ElectionProject.Migrations
{
    [DbContext(typeof(ElectionContext))]
    partial class ElectionContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("ElectionProject.Models.Appeal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<int>("CitizenId")
                        .HasColumnName("citizen_id");

                    b.Property<int?>("DistrictId")
                        .HasColumnName("district_id");

                    b.Property<int?>("ElectionId")
                        .HasColumnName("election_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnName("text");

                    b.Property<int>("TypeId")
                        .HasColumnName("type_id");

                    b.HasKey("Id");

                    b.HasIndex("CitizenId");

                    b.HasIndex("DistrictId");

                    b.HasIndex("ElectionId");

                    b.HasIndex("TypeId");

                    b.ToTable("appeal");
                });

            modelBuilder.Entity("ElectionProject.Models.Candidate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<int>("CitizenId")
                        .HasColumnName("citizen_id");

                    b.Property<int?>("ElectionId")
                        .HasColumnName("election_id");

                    b.Property<int>("Number")
                        .HasColumnName("number");

                    b.HasKey("Id");

                    b.HasIndex("CitizenId");

                    b.HasIndex("ElectionId");

                    b.HasIndex("Number")
                        .IsUnique()
                        .HasName("candidate_number_key");

                    b.ToTable("candidate");
                });

            modelBuilder.Entity("ElectionProject.Models.CheckUpdates", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<int?>("CitizenId")
                        .HasColumnName("citizen_id");

                    b.Property<int?>("UpdatesCount")
                        .HasColumnName("updates_count");

                    b.HasKey("Id");

                    b.HasIndex("CitizenId");

                    b.ToTable("check_updates");
                });

            modelBuilder.Entity("ElectionProject.Models.Circuit", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnName("address")
                        .HasColumnType("character varying(75)");

                    b.Property<string>("Center")
                        .IsRequired()
                        .HasColumnName("center")
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("Address")
                        .IsUnique()
                        .HasName("circuit_address_key");

                    b.ToTable("circuit");
                });

            modelBuilder.Entity("ElectionProject.Models.CircuitHead", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<int?>("CircuitId")
                        .HasColumnName("circuit_id");

                    b.Property<int>("CitizenId")
                        .HasColumnName("citizen_id");

                    b.Property<int?>("ElectionId")
                        .HasColumnName("election_id");

                    b.HasKey("Id");

                    b.HasIndex("CircuitId");

                    b.HasIndex("CitizenId");

                    b.HasIndex("ElectionId");

                    b.ToTable("circuit_head");
                });

            modelBuilder.Entity("ElectionProject.Models.Citizen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnName("birth_date")
                        .HasColumnType("date");

                    b.Property<string>("ConcurrencyStamp");

                    b.Property<int?>("DistrictId")
                        .HasColumnName("district_id");

                    b.Property<string>("Email")
                        .HasColumnName("email")
                        .HasColumnType("character varying(40)");

                    b.Property<bool>("EmailConfirmed");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnName("first_name")
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Ipn")
                        .IsRequired()
                        .HasColumnName("ipn")
                        .HasColumnType("character varying(12)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnName("last_name")
                        .HasColumnType("character varying(30)");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasColumnName("middle_name")
                        .HasColumnType("character varying(30)");

                    b.Property<string>("NormalizedEmail");

                    b.Property<string>("NormalizedUserName");

                    b.Property<string>("Password")
                        .HasColumnName("password")
                        .HasColumnType("character varying(30)");

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.HasIndex("DistrictId");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasName("uniquemail");

                    b.HasIndex("Ipn")
                        .IsUnique()
                        .HasName("citizen_ipn_key");

                    b.HasIndex("Password")
                        .IsUnique()
                        .HasName("uniquepassword");

                    b.ToTable("citizen");
                });

            modelBuilder.Entity("ElectionProject.Models.Complaint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<int?>("DistrictId")
                        .HasColumnName("district_id");

                    b.Property<int?>("ElectionId")
                        .HasColumnName("election_id");

                    b.Property<int>("ObserverId")
                        .HasColumnName("observer_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnName("text");

                    b.Property<int>("TypeId")
                        .HasColumnName("type_id");

                    b.HasKey("Id");

                    b.HasIndex("DistrictId");

                    b.HasIndex("ElectionId");

                    b.HasIndex("ObserverId");

                    b.HasIndex("TypeId");

                    b.ToTable("complaint");
                });

            modelBuilder.Entity("ElectionProject.Models.District", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnName("address")
                        .HasColumnType("character varying(75)");

                    b.Property<int>("CircuitId")
                        .HasColumnName("circuit_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("Address")
                        .IsUnique()
                        .HasName("district_address_key");

                    b.HasIndex("CircuitId");

                    b.ToTable("district");
                });

            modelBuilder.Entity("ElectionProject.Models.DistrictHead", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<int>("CitizenId")
                        .HasColumnName("citizen_id");

                    b.Property<int?>("DistrictId")
                        .HasColumnName("district_id");

                    b.Property<int?>("ElectionId")
                        .HasColumnName("election_id");

                    b.HasKey("Id");

                    b.HasIndex("CitizenId");

                    b.HasIndex("DistrictId");

                    b.HasIndex("ElectionId");

                    b.ToTable("district_head");
                });

            modelBuilder.Entity("ElectionProject.Models.Election", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<DateTime>("EndDate")
                        .HasColumnName("end_date")
                        .HasColumnType("date");

                    b.Property<int>("HeadOfCvk")
                        .HasColumnName("head_of_cvk");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnName("start_date")
                        .HasColumnType("date");

                    b.Property<int>("Tour")
                        .HasColumnName("tour");

                    b.Property<int>("Year")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.HasIndex("HeadOfCvk");

                    b.ToTable("election");
                });

            modelBuilder.Entity("ElectionProject.Models.Observer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<int>("CandidateId")
                        .HasColumnName("candidate_id");

                    b.Property<int>("CitizenId")
                        .HasColumnName("citizen_id");

                    b.Property<int?>("DistrictId")
                        .HasColumnName("district_id");

                    b.Property<int?>("ElectionId")
                        .HasColumnName("election_id");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId");

                    b.HasIndex("CitizenId");

                    b.HasIndex("DistrictId");

                    b.HasIndex("ElectionId");

                    b.ToTable("observer");
                });

            modelBuilder.Entity("ElectionProject.Models.Type", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.ToTable("type");
                });

            modelBuilder.Entity("ElectionProject.Models.Vote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<int>("CandidateId")
                        .HasColumnName("candidate_id");

                    b.Property<int>("CitizenId")
                        .HasColumnName("citizen_id");

                    b.Property<int?>("DistrictId")
                        .HasColumnName("district_id");

                    b.Property<int?>("ElectionId")
                        .HasColumnName("election_id");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId");

                    b.HasIndex("CitizenId")
                        .IsUnique()
                        .HasName("vote_citizen_id_key");

                    b.HasIndex("DistrictId");

                    b.HasIndex("ElectionId");

                    b.ToTable("vote");
                });

            modelBuilder.Entity("ElectionProject.Models.Appeal", b =>
                {
                    b.HasOne("ElectionProject.Models.Citizen", "Citizen")
                        .WithMany("Appeal")
                        .HasForeignKey("CitizenId")
                        .HasConstraintName("appeal_citizen_id_fkey");

                    b.HasOne("ElectionProject.Models.District", "District")
                        .WithMany("Appeal")
                        .HasForeignKey("DistrictId")
                        .HasConstraintName("appeal_district_id_fkey")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ElectionProject.Models.Election", "Election")
                        .WithMany("Appeal")
                        .HasForeignKey("ElectionId")
                        .HasConstraintName("appeal_election_id_fkey")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ElectionProject.Models.Type", "Type")
                        .WithMany("Appeal")
                        .HasForeignKey("TypeId")
                        .HasConstraintName("appeal_type_id_fkey");
                });

            modelBuilder.Entity("ElectionProject.Models.Candidate", b =>
                {
                    b.HasOne("ElectionProject.Models.Citizen", "Citizen")
                        .WithMany("Candidate")
                        .HasForeignKey("CitizenId")
                        .HasConstraintName("candidate_citizen_id_fkey");

                    b.HasOne("ElectionProject.Models.Election", "Election")
                        .WithMany("Candidate")
                        .HasForeignKey("ElectionId")
                        .HasConstraintName("candidate_election_id_fkey")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ElectionProject.Models.CheckUpdates", b =>
                {
                    b.HasOne("ElectionProject.Models.Citizen", "Citizen")
                        .WithMany("CheckUpdates")
                        .HasForeignKey("CitizenId")
                        .HasConstraintName("check_updates_citizen_id_fkey");
                });

            modelBuilder.Entity("ElectionProject.Models.CircuitHead", b =>
                {
                    b.HasOne("ElectionProject.Models.Circuit", "Circuit")
                        .WithMany("CircuitHead")
                        .HasForeignKey("CircuitId")
                        .HasConstraintName("circuit_head_circuit_id_fkey")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ElectionProject.Models.Citizen", "Citizen")
                        .WithMany("CircuitHead")
                        .HasForeignKey("CitizenId")
                        .HasConstraintName("circuit_head_citizen_id_fkey");

                    b.HasOne("ElectionProject.Models.Election", "Election")
                        .WithMany("CircuitHead")
                        .HasForeignKey("ElectionId")
                        .HasConstraintName("circuit_head_election_id_fkey")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ElectionProject.Models.Citizen", b =>
                {
                    b.HasOne("ElectionProject.Models.District", "District")
                        .WithMany("Citizen")
                        .HasForeignKey("DistrictId")
                        .HasConstraintName("fk_citizen_district");
                });

            modelBuilder.Entity("ElectionProject.Models.Complaint", b =>
                {
                    b.HasOne("ElectionProject.Models.District", "District")
                        .WithMany("Complaint")
                        .HasForeignKey("DistrictId")
                        .HasConstraintName("complaint_district_id_fkey")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ElectionProject.Models.Election", "Election")
                        .WithMany("Complaint")
                        .HasForeignKey("ElectionId")
                        .HasConstraintName("complaint_election_id_fkey")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ElectionProject.Models.Observer", "Observer")
                        .WithMany("Complaint")
                        .HasForeignKey("ObserverId")
                        .HasConstraintName("complaint_observer_id_fkey");

                    b.HasOne("ElectionProject.Models.Type", "Type")
                        .WithMany("Complaint")
                        .HasForeignKey("TypeId")
                        .HasConstraintName("complaint_type_id_fkey");
                });

            modelBuilder.Entity("ElectionProject.Models.District", b =>
                {
                    b.HasOne("ElectionProject.Models.Circuit", "Circuit")
                        .WithMany("District")
                        .HasForeignKey("CircuitId")
                        .HasConstraintName("district_circuit_id_fkey");
                });

            modelBuilder.Entity("ElectionProject.Models.DistrictHead", b =>
                {
                    b.HasOne("ElectionProject.Models.Citizen", "Citizen")
                        .WithMany("DistrictHead")
                        .HasForeignKey("CitizenId")
                        .HasConstraintName("district_head_citizen_id_fkey");

                    b.HasOne("ElectionProject.Models.District", "District")
                        .WithMany("DistrictHead")
                        .HasForeignKey("DistrictId")
                        .HasConstraintName("district_head_district_id_fkey")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ElectionProject.Models.Election", "Election")
                        .WithMany("DistrictHead")
                        .HasForeignKey("ElectionId")
                        .HasConstraintName("district_head_election_id_fkey")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ElectionProject.Models.Election", b =>
                {
                    b.HasOne("ElectionProject.Models.Citizen", "HeadOfCvkNavigation")
                        .WithMany("Election")
                        .HasForeignKey("HeadOfCvk")
                        .HasConstraintName("election_head_of_cvk_fkey");
                });

            modelBuilder.Entity("ElectionProject.Models.Observer", b =>
                {
                    b.HasOne("ElectionProject.Models.Candidate", "Candidate")
                        .WithMany("Observer")
                        .HasForeignKey("CandidateId")
                        .HasConstraintName("observer_candidate_id_fkey");

                    b.HasOne("ElectionProject.Models.Citizen", "Citizen")
                        .WithMany("Observer")
                        .HasForeignKey("CitizenId")
                        .HasConstraintName("observer_citizen_id_fkey");

                    b.HasOne("ElectionProject.Models.District", "District")
                        .WithMany("Observer")
                        .HasForeignKey("DistrictId")
                        .HasConstraintName("observer_district_id_fkey")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ElectionProject.Models.Election", "Election")
                        .WithMany("Observer")
                        .HasForeignKey("ElectionId")
                        .HasConstraintName("observer_election_id_fkey")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ElectionProject.Models.Vote", b =>
                {
                    b.HasOne("ElectionProject.Models.Candidate", "Candidate")
                        .WithMany("Vote")
                        .HasForeignKey("CandidateId")
                        .HasConstraintName("vote_candidate_id_fkey");

                    b.HasOne("ElectionProject.Models.Citizen", "Citizen")
                        .WithOne("Vote")
                        .HasForeignKey("ElectionProject.Models.Vote", "CitizenId")
                        .HasConstraintName("vote_citizen_id_fkey");

                    b.HasOne("ElectionProject.Models.District", "District")
                        .WithMany("Vote")
                        .HasForeignKey("DistrictId")
                        .HasConstraintName("vote_district_id_fkey")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ElectionProject.Models.Election", "Election")
                        .WithMany("Vote")
                        .HasForeignKey("ElectionId")
                        .HasConstraintName("vote_election_id_fkey")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
